language: cpp

compiler:
    - clang
    - gcc

notifications:
    email: false
    irc: "chat.freenode.net#stepmania-devs"

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y nasm
    - sudo apt-get install -y libmad0-dev
    - sudo apt-get install -y libgtk2.0-dev
    - sudo apt-get install -y binutils-dev
    - sudo apt-get install -y libasound-dev
    - sudo apt-get install -y libpulse-dev
    - sudo apt-get install -y libjack-dev
    - sudo apt-get install -y libc6-dev
    - sudo apt-get install -y libogg-dev
    - sudo apt-get install -y libvorbis-dev
    - sudo apt-get install -y libbz2-dev
    - sudo apt-get install -y zlib1g-dev
    - sudo apt-get install -y libjpeg8-dev
    - sudo apt-get install -y libpng12-dev
    - sudo apt-get install -y libxtst-dev libxrandr-dev
    - sudo apt-get install -y libglu1-mesa-dev
    - sudo apt-get install -y mesa-common-dev
    - sudo apt-get install -y libglew-dev
    - ./.install-cmake.sh

script:
    - cmake -DWITH_PORTABLE_TOMCRYPT=ON -G 'Unix Makefiles'
    - make
